### ISSUE TITLE
Django 1.8 Support

### ISSUE THREAD

**Issue by rodo** [novafloss/django-json-dbindex#18]
Add tests on Django 1.8

**Comment by rodo** [comment]
Done in https://github.com/novafloss/django-json-dbindex/pull/19

**Comment by k4nar** [comment]
@rodo: Could you tag a new release ? (btw Django 1.7 support was never tagged)

**Comment by rodo** [comment]
Did it https://github.com/novafloss/django-json-dbindex/releases/tag/v1.2.1
